/**
 * This file was auto-generated by the Titanium Module SDK helper for Android Appcelerator Titanium
 * Mobile Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved. Licensed under the
 * terms of the Apache Public License Please see the LICENSE included with this distribution for
 * details.
 *
 */
package com.aeroheart.ti.labelim;


import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;


@Kroll.module(name="Labelim", id="com.aeroheart.ti.labelim")
public class LabelimModule extends KrollModule {
    // Standard Debugging variables
    protected static final String LCAT = "LabelimModule";
    protected static final boolean DBG = TiConfig.LOGD;
    
    @Kroll.constant public static final int ELLIPSIZE_END = 1;
    @Kroll.constant public static final int ELLIPSIZE_MARQUEE = 2;
    @Kroll.constant public static final int ELLIPSIZE_MIDDLE = 3;
    @Kroll.constant public static final int ELLIPSIZE_START = 4;
    
    public LabelimModule() {
        super();
    }
    
    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }
}
